# Polynomial regression

## Formula
$
\begin{bmatrix}
    n       & \sum_{i=0}^{n}  x_{i} & \sum_{i=0}^{n}  x_{i}^{2} & \dots & \sum_{i=0}^{n} x_{i}^{m} \\
    \sum_{i=0}^{n}  x_{i} & \sum_{i=0}^{n}  x_{i}^{2} & \sum_{i=0}^{n} x_{i}^{m} & \dots  & \sum_{i=0}^{n} x_{i}^{(m+1)} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \sum_{i=0}^{n}  x_{m} & \sum_{i=0}^{n}  x_{i}^{(m+1)} & \sum_{i=0}^{n} x_{i}^{(m+2)} & \dots  & \sum_{i=0}^{n} x_{i}^{2m} \\
\end{bmatrix}
$
$
\begin{bmatrix}
    a_{0} \\
    a_{1} \\
    \vdots \\
    a_{m} \\
\end{bmatrix}
$
=
$
\begin{bmatrix}
    \sum_{i=0}^{n} y_{i} \\
    \sum_{i=0}^{n} x_{i}y_{i} \\
    \vdots \\
    \sum_{i=0}^{n} x_{i}^{m}y_{i} \\
\end{bmatrix}
$

## Goal
    To find polynomial equation for given degree and datapoints

In [1]:
from bokeh.io import show
from bokeh.plotting import figure, output_notebook
from bokeh.models import ColumnDataSource
import numpy as np
import numpy.matlib
from numpy.linalg import inv
np.set_printoptions(suppress=True)

## Points

In [2]:
points = numpy.array([[1,2],[3,4],[1,3],[4,3],[6,3],[1,4]])
degree = 5
min_point = -1
max_point = 8

## Algorithm implementation

Let say above formula is represented as

$
\begin{bmatrix}
    X
\end{bmatrix}
$
$\begin{bmatrix}
    A
\end{bmatrix}
$
=
$
\begin{bmatrix}
    Y
\end{bmatrix}
$

we have created 2 empty matrix
$
\begin{bmatrix}
    X
\end{bmatrix}
$
and
$\begin{bmatrix}
    Y
\end{bmatrix}
$


In [3]:
X = np.matlib.empty((degree + 1,degree + 1))
Y = np.matlib.empty((degree + 1,1))

let us calculate
$
\begin{bmatrix}
    X
\end{bmatrix}
$
as using below formula

$
\begin{bmatrix}
    n       & \sum_{i=0}^{n}  x_{i} & \sum_{i=0}^{n}  x_{i}^{2} & \dots & \sum_{i=0}^{n} x_{i}^{m} \\
    \sum_{i=0}^{n}  x_{i} & \sum_{i=0}^{n}  x_{i}^{2} & \sum_{i=0}^{n} x_{i}^{m} & \dots  & \sum_{i=0}^{n} x_{i}^{(m+1)} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \sum_{i=0}^{n}  x_{m} & \sum_{i=0}^{n}  x_{i}^{(m+1)} & \sum_{i=0}^{n} x_{i}^{(m+2)} & \dots  & \sum_{i=0}^{n} x_{i}^{2m} \\
\end{bmatrix}
$

In [4]:
X_elements = []
for num in range(0,(degree + 1)*2 -1):
     X_elements.append(np.sum([np.power(point[0],num) for point in points]))
        
offset = 0
for row in range(0,degree + 1):
    end = offset + degree + 1
    X[row] = X_elements[offset:end]
    offset += 1

print("X")
print("--------------------------")
print(X)


X
--------------------------
[[       6.       16.       64.      310.     1636.     9046.]
 [      16.       64.      310.     1636.     9046.    51484.]
 [      64.      310.     1636.     9046.    51484.   298510.]
 [     310.     1636.     9046.    51484.   298510.  1751716.]
 [    1636.     9046.    51484.   298510.  1751716. 10359526.]
 [    9046.    51484.   298510.  1751716. 10359526. 61573804.]]


let us calculate 
$
\begin{bmatrix}
    Y
\end{bmatrix}
$
as using below formula

$
\begin{bmatrix}
    \sum_{i=0}^{n} y_{i} \\
    \sum_{i=0}^{n} x_{i}y_{i} \\
    \vdots \\
    \sum_{i=0}^{n} x_{i}^{m}y_{i} \\
\end{bmatrix}
$


In [5]:
for num in range(0,degree + 1):
    Y[num] = np.sum([np.power(point[0],num) * point[1] for point in points])

print("Y")
print("--------------------------")
print(Y)


Y
--------------------------
[[   19.]
 [   51.]
 [  201.]
 [  957.]
 [ 4989.]
 [27381.]]


to find 
$
\begin{bmatrix}
    A
\end{bmatrix}
$
we have to multiply both side with inverse of 
$
\begin{bmatrix}
    X
\end{bmatrix}
$

that is

$
\begin{bmatrix}
    X
\end{bmatrix}^{-1}
$
$
\begin{bmatrix}
    X
\end{bmatrix}
$
$
\begin{bmatrix}
    A
\end{bmatrix}
$
=
$
\begin{bmatrix}
    X
\end{bmatrix}^{-1}
$
$
\begin{bmatrix}
    Y
\end{bmatrix}
$


$
\begin{bmatrix}
    A
\end{bmatrix}
$
=
$
\begin{bmatrix}
    X
\end{bmatrix}^{-1}
$
$
\begin{bmatrix}
    Y
\end{bmatrix}
$


In [6]:
X_inv = inv(X)

coeff = X_inv.dot(Y)
print("A")
print("--------------------------")
print(coeff)


A
--------------------------
[[ 0.25      ]
 [ 4.        ]
 [-0.75      ]
 [-0.09375   ]
 [ 0.03320312]
 [-0.00183105]]


## Finding graph points using polynomial equation
$
y = a_{m}x^{m} + a_{m-1}x^{m-1}+ \dots + a_{1}x + a_{0}
$

In [9]:
x = []
y = []
    
for i in range(min_point*10,max_point*10):
    x.append(i/10)
    y.append(np.sum([np.power(i/10,power)*ai[0] for power, ai in enumerate(coeff)]))

## Graph plotting

In [10]:
line_source = ColumnDataSource(data=dict(x=x, y=y))
points_source = ColumnDataSource(data=dict(x=points[:,0], y=points[:,1]))
p = figure(tools="pan,wheel_zoom,reset",plot_width=400, plot_height=400)
p.line('x', 'y', source=line_source) 
p.scatter('x', 'y',source=points_source, line_color="#6666ee", fill_alpha=0.5, size=8)
output_notebook()
show(p)


Loading BokehJS ...